//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskmgrOverlay.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskmgrOverlay.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 TaskmgrOverlay 的本地化字符串。
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main 的本地化字符串。
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At first, I just wanted to play around with the task manager 的本地化字符串。
        /// </summary>
        public static string SettingsPageAboutText {
            get {
                return ResourceManager.GetString("SettingsPageAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About this application 的本地化字符串。
        /// </summary>
        public static string SettingsPageAboutTitle {
            get {
                return ResourceManager.GetString("SettingsPageAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose Theme 的本地化字符串。
        /// </summary>
        public static string SettingsPageChooseThemeText {
            get {
                return ResourceManager.GetString("SettingsPageChooseThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Github Page 的本地化字符串。
        /// </summary>
        public static string SettingsPageGithubLinkText {
            get {
                return ResourceManager.GetString("SettingsPageGithubLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Personalization 的本地化字符串。
        /// </summary>
        public static string SettingsPagePersonalizationTitle {
            get {
                return ResourceManager.GetString("SettingsPagePersonalizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark 的本地化字符串。
        /// </summary>
        public static string SettingsPageRadioButtonDarkTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light 的本地化字符串。
        /// </summary>
        public static string SettingsPageRadioButtonLightTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        public static string SettingsPageRadioButtonWindowsDefaultTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonWindowsDefaultTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go back 的本地化字符串。
        /// </summary>
        public static string ShellGoBackButton {
            get {
                return ResourceManager.GetString("ShellGoBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open or close navigation 的本地化字符串。
        /// </summary>
        public static string ShellHamburgerButtonName {
            get {
                return ResourceManager.GetString("ShellHamburgerButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main 的本地化字符串。
        /// </summary>
        public static string ShellMainPage {
            get {
                return ResourceManager.GetString("ShellMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string ShellSettingsPage {
            get {
                return ResourceManager.GetString("ShellSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        public static string 停止 {
            get {
                return ResourceManager.GetString("停止", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 foreground color 的本地化字符串。
        /// </summary>
        public static string 前景颜色 {
            get {
                return ResourceManager.GetString("前景颜色", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply A weight 的本地化字符串。
        /// </summary>
        public static string 应用A权重 {
            get {
                return ResourceManager.GetString("应用A权重", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply sample compression 的本地化字符串。
        /// </summary>
        public static string 应用采样压缩 {
            get {
                return ResourceManager.GetString("应用采样压缩", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply Gaussian filter 的本地化字符串。
        /// </summary>
        public static string 应用高斯过滤 {
            get {
                return ResourceManager.GetString("应用高斯过滤", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        public static string 开始 {
            get {
                return ResourceManager.GetString("开始", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A new version is available, do you want to update? 的本地化字符串。
        /// </summary>
        public static string 新版本可用是否进行更新 {
            get {
                return ResourceManager.GetString("新版本可用是否进行更新", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum frequency limit 的本地化字符串。
        /// </summary>
        public static string 最高频率限制 {
            get {
                return ResourceManager.GetString("最高频率限制", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find 的本地化字符串。
        /// </summary>
        public static string 查找 {
            get {
                return ResourceManager.GetString("查找", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Capturing audio output 的本地化字符串。
        /// </summary>
        public static string 监听音频输出 {
            get {
                return ResourceManager.GetString("监听音频输出", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drawing width has been fixed (temporarily) 的本地化字符串。
        /// </summary>
        public static string 绘图宽度已经固定暂时的 {
            get {
                return ResourceManager.GetString("绘图宽度已经固定暂时的", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drawing delay 的本地化字符串。
        /// </summary>
        public static string 绘图延迟 {
            get {
                return ResourceManager.GetString("绘图延迟", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Draw height scale 的本地化字符串。
        /// </summary>
        public static string 绘图高度缩放比例 {
            get {
                return ResourceManager.GetString("绘图高度缩放比例", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 background color 的本地化字符串。
        /// </summary>
        public static string 背景颜色 {
            get {
                return ResourceManager.GetString("背景颜色", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get 的本地化字符串。
        /// </summary>
        public static string 获取 {
            get {
                return ResourceManager.GetString("获取", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get the &quot;Task Manager&quot; window 的本地化字符串。
        /// </summary>
        public static string 获取任务管理器窗口 {
            get {
                return ResourceManager.GetString("获取任务管理器窗口", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get the primary and secondary colors of the window 的本地化字符串。
        /// </summary>
        public static string 获取窗口主次颜色 {
            get {
                return ResourceManager.GetString("获取窗口主次颜色", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 transparency 的本地化字符串。
        /// </summary>
        public static string 透明度 {
            get {
                return ResourceManager.GetString("透明度", resourceCulture);
            }
        }
    }
}
